[package]
name = "ant_tsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tsplib = "0.1.0"
ndarray = "0.15.6"
random_choice = "0.3.2"
